// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/v1/dictionary/message": {
            "get": {
                "description": "Returns historical sender and template filters with transports from configured delivery profiles.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin.dictionaries"
                ],
                "summary": "Get message dictionaries",
                "responses": {
                    "200": {
                        "description": "Successfully returned dictionary data",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageDictionaries"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/v1/dictionary/message-recipients": {
            "get": {
                "description": "Returns historical recipient filter suggestions from stored messages, not recipient types or an address book.\nIf the ` + "`" + `search` + "`" + ` parameter is provided, the result is filtered by case‑insensitive substring match.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin.messages"
                ],
                "summary": "Get recipients list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search substring to filter recipients (case‑insensitive). If empty, all recipients are returned.",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of recipient addresses",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/v1/message": {
            "get": {
                "description": "Retrieves a paginated list of messages filtered by status, IDs, recipients, senders, codes, or transports.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin.messages"
                ],
                "summary": "List and filter messages",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to sort by",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order direction (asc/desc)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter by message status array",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter by message UUID array",
                        "name": "ids",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter by recipient array",
                        "name": "recipient",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter by sender ID array",
                        "name": "sender_ids",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter by message code array",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter by transport type array",
                        "name": "transport",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of filtered messages with pagination metadata",
                        "schema": {
                            "$ref": "#/definitions/internal_io_web_endpoint_admin.MessageFinderResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters or form parsing failure",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error while searching for records",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/v1/message/{id}": {
            "get": {
                "description": "Retrieves full message details for a specific record via its UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin.messages"
                ],
                "summary": "Get message by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Unique message UUID identifier",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detailed structural message metadata",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.FullMessageInfo"
                        }
                    },
                    "400": {
                        "description": "Invalid or malformed UUID parameter format",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error or record resolution failure",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/v1/template": {
            "get": {
                "description": "Retrieves a paginated collection of message templates filtered by system code arrays or full-text query matches.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin.templates"
                ],
                "summary": "List and filter templates",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page index parameter",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page item capacity limit",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Target field criteria for ordering records",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Ascending or descending order selection (asc/desc)",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter metrics by unique message system code tokens",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Generic phrase match expression matching structural text",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "System tags (match any)",
                        "name": "system",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Channel tags (match any)",
                        "name": "channel",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Key-value dictionary mapping matching code IDs to schema definitions",
                        "schema": {
                            "$ref": "#/definitions/internal_io_web_endpoint_admin.TemplateFinderResult"
                        }
                    },
                    "400": {
                        "description": "Query validation or structured query parameter parse errors",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal catalog resolution context errors",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates and stores a completely new message configuration blueprint in the repository.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin.templates"
                ],
                "summary": "Create a template",
                "parameters": [
                    {
                        "description": "Structural definition specification metrics payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Template"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Newly registered template model confirmation metadata",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Template"
                        }
                    },
                    "400": {
                        "description": "Corrupted JSON payload body formatting syntax exception",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "500": {
                        "description": "Persistence system errors encountered storing details",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/admin/v1/template/{code}": {
            "put": {
                "description": "Modifies variables, subjects, or raw body layouts of an existing layout found by its explicit target code route component.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin.templates"
                ],
                "summary": "Update a template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target identifying tracking code token context",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updatable structural model fields",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Template"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Refreshed schema specifications entry state details",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Template"
                        }
                    },
                    "400": {
                        "description": "Invalid path payload reference parameters or corrupt body markup values",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "500": {
                        "description": "Database or engine exceptions processing modified models",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/batch/send": {
            "post": {
                "description": "Accepts an array of message payloads, processes their delivery, and registers tracking tasks for each.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public.messages"
                ],
                "summary": "Send multiple messages",
                "parameters": [
                    {
                        "description": "List of messages to be processed and sent",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_io_web_endpoint_public.SenderMessageRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Messages processed and delivery tasks created successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.AddBatchMessageResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON payload or structural error",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error during processing or delivery dispatch",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/enums": {
            "get": {
                "description": "Returns configured transport profiles and valid message, recipient, and subscription codes.\nOmitting a message tag applies only the full opt-out check. Tagged TG and MAX delivery is not currently supported.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public.messages"
                ],
                "summary": "List API reference enums",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_io_web_endpoint_public.Enums"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/message/retry": {
            "post": {
                "description": "Creates a new task to retry a previously failed or pending message. It allows overriding retry policy and schedule.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public.messages"
                ],
                "summary": "Retry a message",
                "parameters": [
                    {
                        "description": "Retry request parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageRetryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message and task details",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.AddMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/preview": {
            "post": {
                "description": "Accepts a raw message template along with dynamic parameters, renders them, and returns the final subject and body preview.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public.messages"
                ],
                "summary": "Preview message",
                "parameters": [
                    {
                        "description": "Message template definition and rendering context",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_io_web_endpoint_public.PreviewMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Template successfully rendered",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessagePreview"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON payload or syntax error",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error during template rendering",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/send": {
            "post": {
                "description": "Accepts a message payload, processes its delivery, and registers the tracking task.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public.messages"
                ],
                "summary": "Send message",
                "parameters": [
                    {
                        "description": "Message details to be processed and sent",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_io_web_endpoint_public.SenderMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message processed and delivery task created successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.AddMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON payload or structural error",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error during processing or delivery dispatch",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/{code}/metadata": {
            "patch": {
                "description": "Objects merge recursively, null deletes keys, arrays and scalars replace values. No per-client ownership enforcement.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public.templates"
                ],
                "summary": "Merge template metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stable template code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Metadata merge patch, maximum 64 KiB",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.TemplateMetadata"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.TemplateMetadata"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/transports": {
            "get": {
                "description": "Available means configured for acceptance, not remote provider health. Credentials are omitted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public.messages"
                ],
                "summary": "List configured delivery profiles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_devian2011_msgchute_internal_service_sender.Transport"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_devian2011_msgchute_internal_dto.AddBatchMessageResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "message": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Message"
                },
                "task": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Task"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.AddMessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Message"
                },
                "task": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Task"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.BackOffParams": {
            "type": "object",
            "additionalProperties": true
        },
        "github_com_devian2011_msgchute_internal_dto.FullMessageInfo": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Message"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.FullTask"
                    }
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.FullTask": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.TaskExecutionResult"
                    }
                },
                "task": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Task"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.Message": {
            "type": "object",
            "required": [
                "recipients",
                "sender_id",
                "transport"
            ],
            "properties": {
                "body": {
                    "type": "string"
                },
                "code": {
                    "description": "Code template code",
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "description": "Meta some additional fields like CC Bcc or Files etc.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageMeta"
                        }
                    ]
                },
                "params": {
                    "description": "Params message params for generate templates",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageParams"
                        }
                    ]
                },
                "recipients": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "retry": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Retry"
                },
                "schedule": {
                    "type": "string"
                },
                "sender_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageStatus"
                },
                "subject": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "transport": {
                    "description": "Transport message provider",
                    "type": "string"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.MessageDictionaries": {
            "type": "object",
            "properties": {
                "sender_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "templates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transports": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.MessageMeta": {
            "type": "object",
            "additionalProperties": {}
        },
        "github_com_devian2011_msgchute_internal_dto.MessageParam": {
            "type": "object",
            "properties": {
                "value": {}
            }
        },
        "github_com_devian2011_msgchute_internal_dto.MessageParams": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageParam"
            }
        },
        "github_com_devian2011_msgchute_internal_dto.MessagePreview": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.MessageRetryRequest": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "retry": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Retry"
                },
                "schedule": {
                    "type": "string"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.MessageStatus": {
            "type": "string",
            "enum": [
                "running",
                "succeeded",
                "failed",
                "declined"
            ],
            "x-enum-varnames": [
                "MessageStatusRunning",
                "MessageStatusSucceeded",
                "MessageStatusFailed",
                "MessageStatusDeclined"
            ]
        },
        "github_com_devian2011_msgchute_internal_dto.Retry": {
            "type": "object",
            "properties": {
                "params": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "retries": {
                    "type": "integer"
                },
                "strategy": {
                    "type": "string"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.Task": {
            "type": "object",
            "properties": {
                "backoff_code": {
                    "type": "string"
                },
                "backoff_params": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.BackOffParams"
                },
                "created_at": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_processed": {
                    "type": "boolean"
                },
                "last_run": {
                    "type": "string"
                },
                "lock_until": {
                    "type": "string"
                },
                "max_retries": {
                    "type": "integer"
                },
                "message_id": {
                    "type": "string"
                },
                "next_run": {
                    "type": "string"
                },
                "retries": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/retrier.TaskStatus"
                },
                "worker": {
                    "type": "string"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.TaskExecutionResult": {
            "type": "object",
            "properties": {
                "execution_time": {
                    "$ref": "#/definitions/time.Duration"
                },
                "id": {
                    "type": "string"
                },
                "is_critical": {
                    "type": "boolean"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "run_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/retrier.TaskStatus"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.Template": {
            "type": "object",
            "required": [
                "body",
                "code",
                "name",
                "subject"
            ],
            "properties": {
                "body": {
                    "type": "string"
                },
                "channels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.TemplateMetadata"
                },
                "name": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.TemplateParams"
                },
                "subject": {
                    "type": "string"
                },
                "systems": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.TemplateMetadata": {
            "type": "object",
            "additionalProperties": {}
        },
        "github_com_devian2011_msgchute_internal_dto.TemplateParam": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                }
            }
        },
        "github_com_devian2011_msgchute_internal_dto.TemplateParams": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.TemplateParam"
            }
        },
        "github_com_devian2011_msgchute_internal_service_sender.Transport": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "code": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "sender": {
                    "type": "string"
                }
            }
        },
        "github_com_devian2011_msgchute_pkg_http_pagination.PageData": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_devian2011_msgchute_pkg_http_response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_io_web_endpoint_admin.MessageFinderResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.FullMessageInfo"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_pagination.PageData"
                }
            }
        },
        "internal_io_web_endpoint_admin.TemplateFinderResult": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_pkg_http_pagination.PageData"
                },
                "templates": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Template"
                    }
                }
            }
        },
        "internal_io_web_endpoint_public.Enums": {
            "type": "object",
            "properties": {
                "message_statuses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageStatus"
                    }
                },
                "recipient_kinds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subscriptions": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_devian2011_msgchute_internal_service_sender.Transport"
                    }
                }
            }
        },
        "internal_io_web_endpoint_public.PreviewMessageRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageParams"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "internal_io_web_endpoint_public.SenderMessageRequest": {
            "type": "object",
            "required": [
                "recipients",
                "sender_id",
                "transport"
            ],
            "properties": {
                "body": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageMeta"
                },
                "params": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.MessageParams"
                },
                "recipients": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "retry": {
                    "$ref": "#/definitions/github_com_devian2011_msgchute_internal_dto.Retry"
                },
                "schedule": {
                    "type": "string"
                },
                "sender_id": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "transport": {
                    "description": "Transport message provider",
                    "type": "string"
                }
            }
        },
        "retrier.TaskStatus": {
            "type": "string",
            "enum": [
                "pending",
                "success",
                "failure"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusSuccess",
                "StatusFailure"
            ]
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Bearer token authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Notification service API",
	Description:      "HTTP API for send any messages",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
